<?xml version="1.0" encoding="utf-8" ?><dwsync><file name="status_codes.pyc" server="198.101.192.11//usr/share/nginx/www/" local="3423069255" remote="20602938439" /><file name="locations.pyc" server="198.101.192.11//usr/share/nginx/www/" local="3423069255" remote="20602938439" /><file name="status_codes.py" server="198.101.192.11//usr/share/nginx/www/" local="3423069255" remote="20602938439" /><file name="util.py" server="198.101.192.11//usr/share/nginx/www/" local="3423069255" remote="20602938439" /><file name="index.py" server="198.101.192.11//usr/share/nginx/www/" local="3423069255" remote="20602938439" /><file name="__init__.pyc" server="198.101.192.11//usr/share/nginx/www/" local="3423069255" remote="20602938439" /><file name="backwardcompat.py" server="198.101.192.11//usr/share/nginx/www/" local="3423069255" remote="20602938439" /><file name="exceptions.pyc" server="198.101.192.11//usr/share/nginx/www/" local="3423069255" remote="20602938439" /><file name="download.pyc" server="198.101.192.11//usr/share/nginx/www/" local="3423069255" remote="20602938439" /><file name="basecommand.py" server="198.101.192.11//usr/share/nginx/www/" local="3423069255" remote="20602938439" /><file name="download.py" server="198.101.192.11//usr/share/nginx/www/" local="3423069255" remote="20602938439" /><file name="__init__.py" server="198.101.192.11//usr/share/nginx/www/" local="3423069255" remote="20602938439" /><file name="runner.pyc" server="198.101.192.11//usr/share/nginx/www/" local="3423069255" remote="20602938439" /><file name="log.pyc" server="198.101.192.11//usr/share/nginx/www/" local="3423069255" remote="20602938439" /><file name="_pkgutil.pyc" server="198.101.192.11//usr/share/nginx/www/" local="3423069255" remote="20602938439" /><file name="index.pyc" server="198.101.192.11//usr/share/nginx/www/" local="3423069255" remote="20602938439" /><file name="_pkgutil.py" server="198.101.192.11//usr/share/nginx/www/" local="3423069255" remote="20602938439" /><file name="runner.py" server="198.101.192.11//usr/share/nginx/www/" local="3423069255" remote="20602938439" /><file name="locations.py" server="198.101.192.11//usr/share/nginx/www/" local="3423069255" remote="20602938439" /><file name="util.pyc" server="198.101.192.11//usr/share/nginx/www/" local="3423069255" remote="20602938439" /><file name="req.pyc" server="198.101.192.11//usr/share/nginx/www/" local="3423069255" remote="20602938439" /><file name="baseparser.pyc" server="198.101.192.11//usr/share/nginx/www/" local="3423069255" remote="20602938439" /><file name="exceptions.py" server="198.101.192.11//usr/share/nginx/www/" local="3423069255" remote="20602938439" /><file name="req.py" server="198.101.192.11//usr/share/nginx/www/" local="3423069255" remote="20602938439" /><file name="basecommand.pyc" server="198.101.192.11//usr/share/nginx/www/" local="3423069255" remote="20602938439" /><file name="backwardcompat.pyc" server="198.101.192.11//usr/share/nginx/www/" local="3423069255" remote="20602938439" /><file name="baseparser.py" server="198.101.192.11//usr/share/nginx/www/" local="3423069255" remote="20602938439" /><file name="log.py" server="198.101.192.11//usr/share/nginx/www/" local="3423069255" remote="20602938439" /></dwsync>